baseURL = "https://colynn.github.io/"
title = "Colynn.Liu"
theme = "LeaveIt"
languageCode = "zh-CN"

paginate = 10000

enableEmoji = true
hasCJKLanguage = true
preserveTaxonomyNames = true

[menu]
  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "书单"
    url = "/readings/"
    weight = 4
  [[menu.main]]
    name = "关于我"
    url = "/aboutme/"
    weight = 5

[params]
    since = 2018
    author = "Colynn.Liu"
    avatar = "/img/home-icon.png"
    subtitle = "回归本真"
    beian = ""
    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'
    hidecredits = true
    description = "Full-Stack DevOps, Be focused and Practical"

[params.social]
    GitHub = "colynn"
    Twitter = "colynnliu"

[permalinks]
    posts = "/:filename/"

[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark]
        [markup.goldmark.extensions]
            definitionList = true
            footnote = true
            linkify = true
            strikethrough = true
            table = true
            taskList = true
            typographer = true
        [markup.goldmark.parser]
            attribute = true
            autoHeadingID = true
            autoHeadingIDType = "github"
        [markup.goldmark.renderer]
            hardWraps = false
            unsafe = true
            xhtml = false
        [markup.highlight]
            codeFences = true
            guessSyntax = false
            hl_Lines = ""
            lineNoStart = 1
            lineNos = false
            lineNumbersInTable = true
            noClasses = true
            style = "colorful"
            tabWidth = 4
        [markup.tableOfContents]
            endLevel = 3
            ordered = false
            startLevel = 2
